services:
  authentication:
    image: ${DOCKER_REGISTRY-}authentication
    build:
      context: .
      dockerfile: Authentication/Dockerfile

  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile


  repertoire:
    image: ${DOCKER_REGISTRY-}repertoire
    build:
      context: .
      dockerfile: Repertoire/Dockerfile


  spectacles:
    image: ${DOCKER_REGISTRY-}spectacles
    build:
      context: .
      dockerfile: Spectacles/Dockerfile


  statistics:
    image: ${DOCKER_REGISTRY-}statistics
    build:
      context: .
      dockerfile: Statistics/Dockerfile


  tickets:
    image: ${DOCKER_REGISTRY-}tickets
    build:
      context: .
      dockerfile: Tickets/Dockerfile

